### PR TITLE
agents are instantiated from simPop.csv with their data including res…

### PR DESCRIPTION
**Pull request by aberke**
…idential and office blocks

- Agents are assigned their src and dst nodes based on their residential and office block IDs
- Agents whose blocks are in "zombie land" are trivially handled by doing nothing
- Still TODO:
 - use amenities and motifs data for agents
 - better handle zombie land

### CODE REVIEW

**Review by agrignard — CHANGES_REQUESTED** [review]
Good job it's getting there. However I have some request before to merge this version

1.keep the current Agent initialisation also so we can quickly switch between the 2 option and compare them. The concept would be to have a "random" initialisation in case we don't have data using the original createAgent function and then having a createAgentFromFile/FromData function that would take in parameter the file.

This is will be  useful to easily compare the two approach and to keep the retro compatibility.
Let's have a global boolean fromData set to true or false depending the mode we want that will call 

2. Also let's keep the grid as a universe variable that we access from universe.grid. It make more sense (and it avoid t to ask every agent to carry this in term of memory) to keep it as a global variable, conceptually this is the environment in which the agent are evolving. Using universe.grid is fine

**Comment by agrignard** [comment]
See Issue #51  https://github.com/CityScope/CS_Cooper-Hewitt/commit/65cbf1fffd182e519a56b5ff6ef74bd55eb00765

we should now be able to write

 if (residentialBlockId > 17 || officeBlockId > 17) {
  srcNode =  getNodeInZombieLand().get(0);
      destNode =  map.getNodeInsideROI().get(0);
    
    }

**Comment by aberke** [comment]
@agrignard thanks for the review and the additions of the zombie land functions.

1. I pushed a new commit to this branch that adds an option to initialize agents from random data instead of from the datafile.

2. About not passing the grid to the agents: I think you're right that it is better to keep the `universe.grid` as a publicly accessible object and not passing it to each agent!  The problem is that at the time of initializing the agent, the `universe` is not yet done being initialized (because the agents are initialized in the same call stack that initializes the universe).  This means that the first time the Agent tries to call `universe.grid` to get the srcNode and destNode from its building ids, the universe is null and there is a `NullPointerException`.
One way to deal with this is to instantiate the Agent's without srcNode or destNode 's set, and then set them on the first call to the Agent's `update()` function.  
What do you think?

I think the way to move forward with respect to incremental changes is: 

- resolving (2)
- then merging these changes
- and then adding the the zombie land functions in the agent code.

**Comment by aberke** [comment]
I pushed another commit to this branch as a possible way to address (2): https://github.com/CityScope/CS_Cooper-Hewitt/pull/54/commits/62f49d3cbbaeb17ae4e4c19f0485fa86f1acca7a

This lazily calls the Agent's init function.  It works, but please let me know what you think about this choice.

**Comment by aberke** [comment]
Sorry for the noise.

I fixed this to remove the lazy call to initAgent and instead call initAgent from the initWorld function.

**Review by agrignard — COMMENTED** [review]
Just to avoid to create a lot of variable that are not used after and to keep the code compact I would replace this  (otherwise it s fine)
`````
      int rBlockId;
      int oBlockId;
      do {
        rBlockId = int(random(24));
        oBlockId =  int(random(24));
      } while (rBlockId == oBlockId);
       String mobilityMotif = "HWH";
      int householdIncome = int(random(12));  // [0, 11]
      int occupationType = int(random(5)) + 1;  // [1, 5]
      int age = int(random(100));
       agents.add(new Agent(networks, glyphsMap, id, grid, rBlockId, oBlockId, mobilityMotif, householdIncome, occupationType, age));
```````

by 
``````
agents.add(new Agent(networks, glyphsMap, id, grid, int(random(24)), int(random(24)), "HWH", int(random(12)), int(random(5))+1, int(random(100)));
``````

**Review by agrignard — APPROVED** [review]

**Comment by agrignard** [comment]
Yep this is why InitAgent function exists (btw it was already questioned here here https://github.com/CityScope/CS_Cooper-Hewitt/issues/9#issuecomment-431776231)

Overall I think it's getting there. We are close to merge this one.

I let you do the final little modif for this one and I'll merge it.

Goog job!

**Pull request merged**
