### PR TITLE
fixes bug where building locations were not being properly updated fr…

### PR DESCRIPTION
**Pull request by aberke**
…om UDP grids message data

other changes
- removed buildingsOnGrid array for simpler data storage

### CODE REVIEW

**Review by agrignard — COMMENTED** [review]
It looks like  the agent is now updating there path however we lost some key feature in this pull request:

1. The interactive building doesn't work anymore, if you put building 20,21, 22 there is no effect anymore
2. When we have no block on the grid  -1 in red was displayed (at least to help debugging) now if there is no block on the grid the id is not displayed anymore.

**Comment by agrignard** [comment]
It is also needed to update id = -1 and >18 regarding issue #86

**Comment by aberke** [comment]
Why need to update -1 and > 18?  What does >18 mean in respect to the grid locations?

**Comment by aberke** [comment]
updated incorporating special building effects + previous changes

**Comment by yasushisakai** [comment]
Merged for testing on the actual table

**Pull request merged**
